### ISSUE TITLE
Generated helpers aren't recognized until renamed to [controller]_helper.js

### ISSUE THREAD

**Issue by absynce** [compoundjs/generators#7]
When helpers are generated for a controller, they do not include the `_helper` suffix.

For example when post crud is created, a file called `[projecthome]/app/helpers/posts.js` is created. However, it does not show up in the view until it is renamed to `[projecthome]/app/helpers/posts_helper.js`.

Although the _helper seems redundant, it's currently required in order for the function to be recognized.

**Comment by 1602** [comment]
Well, it is just naming convention. It was discussed a lot. Why do you think it is reduntant? I think it is necessary to help user easily recognize type of file by it's name, not whole path. Some editors displays just name of file, not full path in quick access list, such as recently used files, opened buffers, tabs, etc..

**Comment by absynce** [comment]
That reasoning for adding the `_helper` suffix makes sense. I didn't mean to sidestep the issue with the comment.

The issue occurs when crud is generated, the `_helper` suffix isn't included by default, so the generator doesn't follow the expected convention.

Example:

```
$ compound g crud user email givenName surname password active createdOn
[...]
create  app/views/users/edit.ejs
create  app/views/users/index.ejs
create  app/helpers/users.js  <-- It doesn't have the _helper suffix when generated.
create  test/controllers/users_controller.test.js
exists  test/init.js
patch   config/routes.js
```

Then I have to rename `app/helpers/users.js` to `app/helpers/users_helper.js` in order for it to be recognized.

**Comment by 1602** [comment]
Ops, sorry I didn't get  the issue correctly. I will look into it thanks for spotting. Looks like regression.
