### ISSUE TITLE
Admin scaffold

### ISSUE THREAD

**Issue by erickbelfy** [compoundjs/generators#8]
We can provide an administration module like django to consume all CRUD files, and create a default user table for authentication?

**Comment by 1602** [comment]
I don't think it's for generator. Actually I already started project based
on jugglingdb and compoundjs that will provide admin interface to database,
but now it's frozen, waiting for some developer love.

**Comment by erickbelfy** [comment]
I was going to start a project like that, please show me our repository to contribute, i like the idea :)

**Comment by 1602** [comment]
https://github.com/anatoliychakkaev/ui-juggling

Please do not use as base. Just read to get an idea, it's outdated, as you
can see. So easier to build from scratch.

On 4 February 2014 17:02, Erick Belfort notifications@github.com wrote:

> I was going to start a project like that, please show me our repository to
> contribute, i like the idea :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/compoundjs/generators/issues/8#issuecomment-34081613
> .

## 

Thanks,
Anatoliy Chakkaev

**Comment by erickbelfy** [comment]
Ok i will read the documents and start describe some goals and share with you.
